# createCodebook.R
#
# Reset R environment
# http://stackoverflow.com/questions/14187048/r-language-clean-variables-and-close-connections
closeAllConnections()
rm(list=ls())

library(xtable)

Variable <- c("tBodyAccXMean",
              "tBodyAccYMean",
              "tBodyAccZMean",
              "tBodyAccXStd",
              "tBodyAccYStd",
              "tBodyAccZStd",
              "tGravityAccXMean",
              "tGravityAccYMean",
              "tGravityAccZMean",
              "tGravityAccXStd",
              "tGravityAccYStd",
              "tGravityAccZStd",
              "tBodyAccJerkXMean",
              "tBodyAccJerkYMean",
              "tBodyAccJerkZMean",
              "tBodyAccJerkXStd",
              "tBodyAccJerkYStd",
              "tBodyAccJerkZStd",
              "tBodyGyroXMean",
              "tBodyGyroYMean",
              "tBodyGyroZMean",
              "tBodyGyroXStd",                      
              "tBodyGyroYStd",
              "tBodyGyroZStd",
              "tBodyGyroJerkXMean",
              "tBodyGyroJerkYMean",                 
              "tBodyGyroJerkZMean",
              "tBodyGyroJerkXStd",                  
              "tBodyGyroJerkYStd",
              "tBodyGyroJerkZStd",
              "tBodyAccMagMean",
              "tBodyAccMagStd",
              "tGravityAccMagMean",
              "tGravityAccMagStd",
              "tBodyAccJerkMagMean",
              "tBodyAccJerkMagStd",
              "tBodyGyroMagMean",
              "tBodyGyroMagStd",
              "tBodyGyroJerkMagMean",
              "tBodyGyroJerkMagStd",
              "fBodyAccXMean",
              "fBodyAccYMean",
              "fBodyAccZMean",
              "fBodyAccXStd",
              "fBodyAccYStd",
              "fBodyAccZStd",
              "fBodyAccXMeanFreq",
              "fBodyAccYMeanFreq",
              "fBodyAccZMeanFreq",
              "fBodyAccJerkXMean",
              "fBodyAccJerkYMean",
              "fBodyAccJerkZMean",
              "fBodyAccJerkXStd",
              "fBodyAccJerkYStd",
              "fBodyAccJerkZStd",
              "fBodyAccJerkXMeanFreq",
              "fBodyAccJerkYMeanFreq",
              "fBodyAccJerkZMeanFreq",
              "fBodyGyroXMean",
              "fBodyGyroYMean",
              "fBodyGyroZMean",
              "fBodyGyroXStd",
              "fBodyGyroYStd",
              "fBodyGyroZStd",
              "fBodyGyroXMeanFreq",
              "fBodyGyroYMeanFreq",
              "fBodyGyroZMeanFreq",
              "fBodyAccMagMean",
              "fBodyAccMagStd",
              "fBodyAccMagMeanFreq",
              "fBodyBodyAccJerkMagMean",
              "fBodyBodyAccJerkMagStd",
              "fBodyBodyAccJerkMagMeanFreq",
              "fBodyBodyGyroMagMean",
              "fBodyBodyGyroMagStd",
              "fBodyBodyGyroMagMeanFreq",
              "fBodyBodyGyroJerkMagMean",
              "fBodyBodyGyroJerkMagStd",
              "fBodyBodyGyroJerkMagMeanFreq",
              "angle.tBodyAccMean.gravity",
              "angle.tBodyAccJerkMean.gravityMean",
              "angle.tBodyGyroMean.gravityMean",
              "angle.tBodyGyroJerkMean.gravityMean",
              "angle.X.gravityMean",
              "angle.Y.gravityMean",                 
              "angle.Z.gravityMean")

Domain <- c("Time",
            "Time",
            "Time",
            "Time",
            "Time",
            "Time",
            "Time",
            "Time",
            "Time",
            "Time",
            "Time",
            "Time",
            "Time",
            "Time",
            "Time",
            "Time",
            "Time",
            "Time",
            "Time",
            "Time",
            "Time",
            "Time",
            "Time",
            "Time",
            "Time",
            "Time",
            "Time",
            "Time",
            "Time",
            "Time",
            "Time",
            "Time",
            "Time",
            "Time",
            "Time",
            "Time",
            "Time",
            "Time",
            "Time",
            "Time",
            "Frequency",
            "Frequency",
            "Frequency",
            "Frequency",
            "Frequency",
            "Frequency",
            "Frequency",
            "Frequency",
            "Frequency",
            "Frequency",
            "Frequency",
            "Frequency",
            "Frequency",
            "Frequency",
            "Frequency",
            "Frequency",
            "Frequency",
            "Frequency",
            "Frequency",
            "Frequency",
            "Frequency",
            "Frequency",
            "Frequency",
            "Frequency",
            "Frequency",
            "Frequency",
            "Frequency",
            "Frequency",
            "Frequency",
            "Frequency",
            "Frequency",
            "Frequency",
            "Frequency",
            "Frequency",
            "Frequency",
            "Frequency",
            "Frequency",
            "Frequency",
            "Frequency",
            "Time",
            "Time",
            "Time",
            "Time",
            "Time",
            "Time",
            "Time")

Description <- c("Body x-axis mean acceleration",
                 "Body y-axis mean acceleration",
                 "Body z-axis mean acceleration",
                 "Body x-axis acceleration standard deviation",
                 "Body y-axis acceleration standard deviation",
                 "Body z-axis acceleration standard deviation",
                 "Gravity x-axis mean acceleration",
                 "Gravity y-axis mean acceleration",
                 "Gravity z-axis mean acceleration",
                 "Gravity x-axis acceleration standard deviation",
                 "Gravity y-axis acceleration standard deviation",
                 "Gravity z-axis acceleration standard deviation",
                 "Body mean x-axis acceleration derivative",
                 "Body mean y-axis acceleration derivative",
                 "Body mean z-axis acceleration derivative",
                 "Body x-axis acceleration derivative standard deviation",
                 "Body y-axis acceleration derivative standard deviation",
                 "Body z-axis acceleration derivative standard deviation",
                 "Body mean x-axis gyroscope",
                 "Body mean y-axis gyroscope",
                 "Body mean z-axis gyroscope",
                 "Body x-axis gyroscope standard deviation",
                 "Body y-axis gyroscope standard deviation",
                 "Body z-axis gyroscope standard deviation",
                 "Body mean x-axis gyroscope derivative",
                 "Body mean y-axis gyroscope derivative",
                 "Body mean z-axis gyroscope derivative",
                 "Body x-axis gyroscope derivative standard deviation",
                 "Body y-axis gyroscope derivative standard deviation",
                 "Body z-axis gyroscope derivative standard deviation",
                 "Body mean acceleration magnitude",
                 "Body acceleration standard deviation",
                 "Gravity mean acceleration magnitude",
                 "Gravity acceleration magnitude standard deviation",
                 "Body mean acceleration derivative magnitude",
                 "Body acceleration derivative magnitude standard deviation",
                 "Body mean gyroscope magnitude",
                 "Body gyroscope magnitude standard deviation",
                 "Body mean gyroscope derivative magnitude",
                 "Body gyroscope derivative magnitude standard deviation",
                 "Mean FFT(Body x-axis acceleration) magnitude",
                 "Mean FFT(Body y-axis acceleration) magnitude",
                 "Mean FFT(Body z-axis acceleration) magnitude",
                 "FFT(Body x-axis acceleration) magnitude standard deviation",
                 "FFT(Body y-axis acceleration) magnitude standard deviation",
                 "FFT(Body z-axis acceleration) magnitude standard deviation",
                 "Body mean x-axis acceleration frequency",
                 "Body mean y-axis acceleration frequency",
                 "Body mean z-axis acceleration frequency",
                 "Mean FFT(Body x-axis acceleration derivative) magnitude",
                 "Mean FFT(Body y-axis acceleration derivative) magnitude",
                 "Mean FFT(Body z-axis acceleration derivative) magnitude",
                 "FFT(Body x-axis acceleration derivative) magnitude standard deviation",
                 "FFT(Body y-axis acceleration derivative) magnitude standard deviation",
                 "FFT(Body z-axis acceleration derivative) magnitude standard deviation",
                 "Body mean x-axis acceleration derivative frequency",
                 "Body mean y-axis acceleration derivative frequency",
                 "Body mean z-axis acceleration derivative frequency",
                 "Mean FFT(Body x-axis gyroscope) magnitude",
                 "Mean FFT(Body y-axis gyroscope) magnitude",
                 "Mean FFT(Body z-axis gyroscope) magnitude",
                 "FFT(Body x-axis gyroscope) magnitude standard deviation",
                 "FFT(Body y-axis gyroscope) magnitude standard deviation",
                 "FFT(Body z-axis gyroscope) magnitude standard deviation",
                 "Body x-axis gyroscope mean frequency",
                 "Body y-axis gyroscope mean frequency",
                 "Body z-axis gyroscope mean frequency",
                 "Mean FFT(Body acceleration) magnitude",
                 "FFT(Body acceleration) magnitude standard deviation",
                 "Body acceleration magnitude mean frequency",
                 "Mean FFT(Body acceleration derivative) magnitude",
                 "FFT(Body acceleration derivative) standard deviation",
                 "Body acceleration derivative mean frequency",
                 "Mean FFT(Body gyroscope) magnitude",
                 "FFT(Body gyroscope) magnitude standard deviation",
                 "Body gyroscope magnitude mean frequency",
                 "Mean FFT(Body gyroscope derivative) magnitude",
                 "FFT(Body gyroscope derivative) magnitude standard deviation",
                 "Body gyroscope derivative magnitude mean frequency",
                 "angle(Body mean acceleration, gravity)",
                 "angle(Body mean acceleration derivative, mean gravity)",
                 "angle(Body mean gyroscope, mean gravity)",
                 "angle(Body mean gyroscope derivative, mean gravity)",
                 "angle(X-axis, gravityMean)",
                 "angle(Y-axis, gravityMean)",
                 "angle(Z-axis, gravityMean)")

# Technical reference:
# -------------------
# http://blog.revolutionanalytics.com/2010/02/making-publicationready-tables-with-xtable.html
# http://stackoverflow.com/questions/6295579/print-xtable-only-displays-doesnt-save-to-disk
codebook <- xtable(data.frame(Variable,Domain,Description))
print(codebook,type="html",file="codebook.html")

featureName <- c("tBodyAcc-mean()-X",
                 "tBodyAcc-arCoeff()-X,2",
                 "tBodyAcc-correlation()-X,Y",
                 "tBodyGyroJerkMag-arCoeff()2",
                 "fBodyAcc-bandsEnergy()-25,48",
                 "angle(tBodyGyroMean,gravityMean)",
                 "fBodyBodyGyroJerkMag-skewness()",
                 "fBodyAccJerk-maxInds-Y")

regularExpressions <- c("([A-Za-z]+)-([A-Za-z]+)[(][)]-([A-Z])",
                        "([A-Za-z]+)-([A-Za-z]+)[(][)]-([A-Z]),([0-9])",
                        "([A-Za-z]+)-([A-Za-z]+)[(][)]-([A-Z]),([A-Z])",
                        "([A-Za-z]+)-([A-Za-z]+)[(][)]([0-9])",
                        "([A-Za-z]+)-([A-Za-z]+)[(][)]-([0-9]+),([0-9]+)",
                        "([a-z]+)[(]([A-Za-z]+)[)]*,([A-Za-z]+)[)]",
                        "([A-Za-z]+)-([A-Za-z]+)[(]*[)]*",
                        "([A-Za-z]+)-([A-Za-z]+)-([A-Z])")

transformedFeatureName <- c("tBodyAccXMean",
                            "tBodyAccArCoeffX2",
                            "tBodyAccXYCorrelation",
                            "tBodyGyroJerkMagArCoeff2",
                            "fBodyAccBandsEnergy.25.48",
                            "angle.tBodyGyroMean.gravityMean",
                            "fBodyBodyGyroJerkMagSkewness",
                            "fBodyAccJerkYMaxInds")

featureNames <- xtable(data.frame(featureName,
                                  regularExpressions,
                                  transformedFeatureName))
print(featureNames,
      type="html",
      file="featureNames.html",
      row.names=FALSE)